### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by avidsapp** [henrikwirth/gatsby-starter-wordpress-twenty-twenty#14]
Full error:

```
Cannot read property 'replace' of undefined



  TypeError: Cannot read property 'replace' of undefined
  
  - process-node.js:118 find
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:118:65
  
  - Array.find
  
  - process-node.js:108 pickNodeBySourceUrlOrCheerioImg
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:108:34
  
  - process-node.js:221 fetchNodeHtmlImageMediaItemNodes
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:221:21
  
  - process-node.js:477 replaceNodeHtmlImages
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:477:44
  
  - process-node.js:816 processNodeString
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:816:18
  
  - process-node.js:856 processNode
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/process-node.js:856:31
  
  - create-nodes.js:42 
    [gatsby]/[gatsby-source-wordpress-experimental]/src/steps/source-nodes/create-nodes/create-nodes.js:42:12
  
  - index.js:163 run
    [gatsby]/[p-queue]/dist/index.js:163:29
  

not finished source and transform nodes - 10.474s
not finished  gatsby-source-wordpress  fetching nodes - 10.385s - 114 total
not finished  gatsby-source-wordpress  creating nodes - 6.844s
not finished  gatsby-source-wordpress  MediaItem - 6.845s - fetched 40
not finished Generating image thumbnails - 6.184s
```

Seems to hangup around the 40th media file. Error surfaced after updating blog posts for the first time.

**Comment by henrikwirth** [comment]
@avidsapp could be that some of your data on the WP side of things is corrupted?

**Comment by avidsapp** [comment]
@henrikwirth that may be the case. Is there a better way to determine which file specifically is causing the issue?

Couple of notes:

1. At one point, I turned off the WP settings from "organize by year and month". I have since re-uploaded and replaced all attachments. Still throwing the error
2. I removed all media from the WP server
2. Some media seemed to remain so I deleted from server cli
4. Throws this errors - likely because attachments aren't present.
```
MaxRedirectsError: Redirected 10 times. Aborting.
    at Request._onResponseBase (.../gatsby-wordpress-official/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:850:35)
    at Request._onResponse (.../gatsby-wordpress-official/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:931:24)
    at ClientRequest.<anonymous> (.../gatsby-wordpress-official/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:945:23)
    at Object.onceWrapper (node:events:434:26)
    at ClientRequest.emit (node:events:339:22)
    at ClientRequest.origin.emit (.../gatsby-wordpress-official/node_modules/gatsby-source-wordpress/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:652:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:126:17)
    at TLSSocket.socketOnData (node:_http_client:518:22)
    at TLSSocket.emit (node:events:327:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:218:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:192:23) {
  code: undefined,
  timings: undefined
}
```
and

```
warn Received the below error when trying to fetch
https://example.com/wp-content/uploads/example.jpg
from Page #2153 "Example Page"

https://example.com/wp-admin/post.php?post=2153&action=edit
```
5. I updated from `gatsby-source-wordpress-experimental` to v4.0.1 of `gatsby-source-wordpress` and still throws the same error.
6. Tried from the default gatsby-wordpress-starter and throws same error, so likely media related
7. Tried uploading all media (including .pdf). At times it hung up on the .pdfs, so tried without .pdfs on server. Same error.

**Comment by henrikwirth** [comment]
@avidsapp I just updated this starter to newest WPGatsby, Gatsby, gatsby-source-wordpress and WPGraphQL versions. Not sure if that might help in your case.

I have the feeling, that in some of your content are resources referenced, that are not there anymore. Check your Posts/Pages, sometimes just resaving them helps to get rid of the reference.

**Comment by henrikwirth** [comment]
You can also try searching your database for /wp-content/uploads/example.jpg and see where it still exists.

**Comment by avidsapp** [comment]
Resolved. For anybody that runs across a similar problem, I was able to track down the corrupted file by wiping the WP server and redoing it by importing edited xml data for pages/posts/media. The initial `gatsby develop` stopped when creating the problem page. Changed the media on this page and the process completed with an error:

```
ERROR #gatsby-source-wordpress_gatsby-plugin-sharp-20000 

Failed to retrieve metadata from image .../gatsby/.cache/caches/gatsby-source-wordpress/48f5da48c8e6c29601b6ab32c3c14b38/problem-image.jpg

Error: Input file contains unsupported image format
```

After deleting the problem-image.jpg and `gatsby clean`:

```
ERROR #gatsby-source-wordpress_gatsby-plugin-sharp-20000 

Failed to retrieve metadata from image .../gatsby/.cache/caches/gatsby-source-wordpress/d41d8cd98f00b204e9800998ecf8427e/null.jpg

Error: Input file contains unsupported image format
```

Manually deleted this cache file and build completes just fine.
